<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>io.github.easy4j</groupId>
	<artifactId>jmxtrans-integration</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	
	<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<scm>
		<connection>scm:git:git@github.com:vindell/${project.artifactId}.git</connection>
		<developerConnection>scm:git:git@github.com:vindell/${project.artifactId}.git</developerConnection>
		<url>git@github.com:vindell/${project.artifactId}.git</url>
	</scm>
	
	 <developers>
        <developer>
        	<id>001</id>
            <name>vindell</name>
            <email>hnxyhcwdl1003@163.com</email>
        </developer>
    </developers> 
	
	<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<name>Maven Snapshots Repository</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<name>Maven Central Staging Repository</name>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
		</repository>
	</distributionManagement>
    
	<build>
		<pluginManagement>
			<plugins>
				  
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.6.1</version> 
					  
					<configuration>
						<release>${java.version}</release>
                        <defaultLibBundleDir>lib</defaultLibBundleDir>
						
						
						
						<encoding>${project.build.sourceEncoding}</encoding>
						
						<maxmem>512M</maxmem>
					</configuration>
				</plugin>
				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.0.1</version>
					  
					<configuration>
						
						<encoding>${project.build.sourceEncoding}</encoding>
					</configuration>
					
					<executions>
						<execution>
							<id>copy-resources</id>
							<phase>validate</phase>
							<goals>
								<goal>copy-resources</goal>
							</goals>
							<configuration>
								<outputDirectory>${basedir}/target/classes</outputDirectory>
								<resources>
									<resource>
										<directory>src/main/resources</directory>
										
									</resource>
								</resources>
							</configuration>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>findbugs-maven-plugin</artifactId>
					<version>3.0.4</version>
					<executions>
						<execution>
							<phase>verify</phase>
							<goals>
								<goal>check</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				  
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.5.2</version>
					<configuration>
						
						<skip>false</skip>
						<skipTests>false</skipTests>
						
						<forkMode>once</forkMode>
						<argLine>-Xmx1024m   -Dfile.encoding=UTF-8</argLine> 
						<additionalClasspathElements> 
			                <additionalClasspathElement>${basedir}/target/test-classes</additionalClasspathElement>  
			            </additionalClasspathElements>  
			            <includes>  
			                <include>**/*Test.java</include> 
			            </includes> 
                        <excludes>
                            <exclude>**/TestBean.java</exclude>
                        </excludes>
					</configuration>					
				</plugin>
				 
				<plugin>  					 
					<groupId>org.apache.maven.plugins</groupId>  
					<artifactId>maven-jar-plugin</artifactId>  
					<version>3.0.2</version>  
					<configuration> 
						<encoding>${project.build.sourceEncoding}</encoding>
						<skipIfEmpty>true</skipIfEmpty> 
	                    <archive>  
                    	 	<manifest>
								<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
								<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
							</manifest>
							
							
	                    </archive>  
	                </configuration>  
				</plugin> 
				 
				<plugin>  					 
					<groupId>org.apache.maven.plugins</groupId>  
					<artifactId>maven-install-plugin</artifactId>  
					<version>2.5.2</version>  
				</plugin> 
				 
				<plugin>  
		            <groupId>org.apache.maven.plugins</groupId>  
		            <artifactId>maven-deploy-plugin</artifactId>  
		            <version>2.8.2</version>  
		        </plugin>
								
				<plugin>
					 <groupId>org.apache.maven.plugins</groupId>
					 <artifactId>maven-source-plugin</artifactId>
					 <version>3.0.1</version> 
					 
					 <configuration>  
					 	 <testFailureIgnore>true</testFailureIgnore>
					 	 
	                     <attach>true</attach>  
	                     <encoding>${project.build.sourceEncoding}</encoding>  
	                 </configuration> 
					 <executions>
						 <execution>
							 <id>attach-sources</id>
							 <phase>package</phase>
							 <goals>
							 	
								
								<goal>jar-no-fork</goal>
							 </goals>
						 </execution>
					 </executions>
				</plugin>
					
				<plugin>  
		            <groupId>org.apache.maven.plugins</groupId>  
		            <artifactId>maven-javadoc-plugin</artifactId>  
		            <version>2.10.4</version> 
					<configuration>  
	                    <aggregate>true</aggregate>  
	                    <argLine>-Dfile.encoding=UTF-8</argLine>
                       	<charset>${project.build.sourceEncoding}</charset> 
                        <encoding>${project.build.sourceEncoding}</encoding> 
                        <docencoding>${project.build.sourceEncoding}</docencoding> 
	                </configuration>
					<executions>
						<execution>
							<id>attach-javadocs</id>
							<phase>package</phase>
							<goals>
								<goal>jar</goal>
							</goals>
						</execution>
					</executions>				
		        </plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
			</plugin>
			  
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
			</plugin> 
			
			<plugin>  					 
				<groupId>org.apache.maven.plugins</groupId>  
				<artifactId>maven-jar-plugin</artifactId>  
			</plugin> 
			 
			<plugin>  					 
				<groupId>org.apache.maven.plugins</groupId>  
				<artifactId>maven-install-plugin</artifactId>  
			</plugin> 
			 
			<plugin>  
	            <groupId>org.apache.maven.plugins</groupId>  
	            <artifactId>maven-deploy-plugin</artifactId>  
	        </plugin>	
							
			<plugin>
				 <groupId>org.apache.maven.plugins</groupId>
				 <artifactId>maven-source-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<jackson.version>2.8.8</jackson.version>
		<jmxtrans.versin>270</jmxtrans.versin>
		<junit.version>4.12</junit.version>
		<servlet-api.version>3.0.1</servlet-api.version>
		<slf4j.version>1.7.21</slf4j.version>
		<spring.version>4.3.11.RELEASE</spring.version>
		<log4j.version>1.2.17</log4j.version>
		<druid.version>1.0.31</druid.version>
	<java.version>21</java.version><maven.compiler.release>${java.version}</maven.compiler.release><maven-jacoco-plugin.version>0.8.15</maven-jacoco-plugin.version><maven-central-publishing-plugin.version>0.11.0</maven-central-publishing-plugin.version></properties>
	
	<dependencyManagement>
		<dependencies>

			

			
			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<version>${junit.version}</version>
			</dependency>

			

			
			<dependency>
				<groupId>javax.servlet</groupId>
				<artifactId>javax.servlet-api</artifactId>
				<version>${servlet-api.version}</version>
			</dependency>

			

			
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-api</artifactId>
				<version>${slf4j.version}</version>
			</dependency>
			
			
			
			
			<dependency>
				<groupId>log4j</groupId>
				<artifactId>log4j</artifactId>
				<version>${log4j.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-log4j12</artifactId>
				<version>${slf4j.version}</version>
			</dependency>

			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-core</artifactId>
				<version>${jackson.version}</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-annotations</artifactId>
				<version>${jackson.version}</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-databind</artifactId>
				<version>${jackson.version}</version>
			</dependency>

			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-core</artifactId>
				<version>${jmxtrans.versin}</version>
				<exclusions>
					<exclusion>
						<artifactId>tools</artifactId>
						<groupId>com.sun</groupId>
					</exclusion>
				</exclusions>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-utils</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-output-core</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-output-jrobin</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-output-ganglia</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-output-elastic</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-output-log4j</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-output-velocity</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-output-kafka</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-output-cloudwatch</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-output-influxdb</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-examples</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans</groupId>
				<artifactId>jmxtrans-test-utils</artifactId>
				<version>${jmxtrans.versin}</version>
			</dependency>
			<dependency>
				<groupId>org.jmxtrans.embedded</groupId>
				<artifactId>embedded-jmxtrans</artifactId>
				<version>1.2.1</version>
				<exclusions>
					<exclusion>
						<artifactId>tools</artifactId>
						<groupId>com.sun</groupId>
					</exclusion>
				</exclusions>
			</dependency>
			
			<dependency>
				<groupId>org.jmxtrans.agent</groupId>
				<artifactId>jmxtrans-agent</artifactId>
				<version>1.2.5</version>
				<exclusions>
					<exclusion>
						<artifactId>tools</artifactId>
						<groupId>com.sun</groupId>
					</exclusion>
				</exclusions>
			</dependency>
			
			
			<dependency>
			    <groupId>com.alibaba</groupId>
			    <artifactId>druid</artifactId>
			    <version>${druid.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.influxdb</groupId>
				<artifactId>influxdb-java</artifactId>
				<version>2.4</version>
			</dependency>
			
		</dependencies>
	</dependencyManagement>

	<dependencies>
	
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<scope>test</scope>
		</dependency>
		
		
		
		<dependency>
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>annotations</artifactId>
			<version>3.0.0</version>
			<optional>true</optional>
		</dependency>
		
		
		
		<dependency>
		    <groupId>com.alibaba</groupId>
		    <artifactId>druid</artifactId>
		    <scope>provided</scope>
		</dependency>
		
		
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.jmxtrans.embedded</groupId>
			<artifactId>embedded-jmxtrans</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>tools</artifactId>
					<groupId>com.sun</groupId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-databind</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		
		
	</dependencies>

</project>